/* eslint-disable import/no-anonymous-default-export */
// UI Types:
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const SET_VIEWPORT_DIMENSIONS = "SET_VIEWPORT_DIMENSIONS";
export const SET_UI_MESSAGE = "SET_UI_MESSAGE";
export const SET_COLOR_SELECT_OPTIONS = "SET_COLOR_SELECT_OPTIONS";
export const CLOSE_COLOR_SELECT = "CLOSE_COLOR_SELECT";
export const SYNC_ADD_EVENT_FORM_TO_REDUX = "SYNC_ADD_EVENT_FORM_TO_REDUX";

// Notifications and Interactions Types:
export const SHOW_TOAST_NOTIFICATION = "SHOW_TOAST_NOTIFICATION";
export const CANCEL_TOAST_NOTIFICATION = "CANCEL_TOAST_NOTIFICATION";
export const RESET_TOAST_NOTIFICATION = "RESET_TOAST_NOTIFICATION";

// Network Types:
export const IS_LOADING = "IS_LOADING";
export const NETWORK_RESPONSE = "NETWORK_RESPONSE";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const TIMER_START = "TIMER_START";
export const TIMER_END = "TIMER_END";

// User Actions:
export const ADD_NEW_USER = "ADD_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_USER_DATA = "GET_USER_DATA";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const DELETE_USER = "DELETE_USER";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";

// ERRORS:
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
export const ERROR_USER_ALREADY_EXISTS = "ERROR_USER_ALREADY_EXISTS";
export const ERROR_USER_NOT_AUTHORIZED = "ERROR_USER_NOT_AUTHORIZED";
export const ERROR_USER_PASSWORD_INCORRECT = "ERROR_USER_PASSWORD_INCORRECT";
export const SERVER_ERROR = "SERVER_ERROR";

// Setting types:
export const UPDATE_USER_SETTINGS = "UPDATE_USER_SETTINGS";
export const UPDATE_TILE_COLOR_SETTINGS = "UPDATE_TILE_COLOR_SETTINGS";
